<?php

use Lastfm\Service\Client;
use Lastfm\Service\Album;

/**
 * Test class for Album.
 * Generated by PHPUnit on 2011-11-09 at 17:32:42.
 */
class AlbumTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lastfm\Service\Album
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Album;
        $client = new Client();
        $client->setApiKey('b25b959554ed76058ac220b7b2e0a026'); // Demo api key provided by lastfm
        $this->object->setClient($client);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetInfo()
    {
        $this->object->getInfo('Whatever people say that i am that\'s what i am not', 'Arctic Monkeys');
    }

    /**
     * If no exceptions are raised things are ok
     */
    public function testSetClient()
    {
        $album = new Album;
        $client = new \Lastfm\Service\Client();
        $album->setClient($client);
    }

    /**
     * @depends testSetClient
     */
    public function testGetClient()
    {
        $album = new Album;
        $client = new \Lastfm\Service\Client();
        $album->setClient($client);

        $this->assertInstanceOf('\Lastfm\Service\Client', $album->getClient());
    }
}
