<?php

use Lastfm\Service\Client;

/**
 * Test class for Client.
 * Generated by PHPUnit on 2011-11-09 at 16:59:23.
 */
class ClientTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lastfm\Service\Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Client();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSetApiKey()
    {
        $this->object->setApiKey('foo');
        $this->assertEquals('foo', $this->object->getApiKey());
    }

    public function testGetApiKey()
    {
        $this->assertEquals('', $this->object->getApiKey());
    }

    public function testCall()
    {
        $this->object->setApiKey('b25b959554ed76058ac220b7b2e0a026'); // API key from last.fm api demo
        $result = $this->object->call('album.search', array('album' => 'believe'));
        $this->assertInstanceOf('SimpleXmlElement', $result);
    }
}
